### PR TITLE
fix: Improve browser-support for compress middleware

### LINKED ISSUE #6380: Use in SAPUI5 application (was working on version 4.4.0)
### Describe the Bug

Hi Colleagues,by following the issue https://github.com/SAP/cloud-sdk-js/issues/704 , I know the support for UI5 was not intended but we were able to run it with https://github.com/ui5-community/ui5-ecosystem-showcase/issues/1064#issuecomment-2700364767 . It works with version @sap-cloud-sdk/http-client 4.4.0, but later versions 5.x breaks due to zlib.brotliCompress being undefined (compress.request.middleware.js).

const brotliCompress = (0, node_util_1.promisify)(zlib.brotliCompress);

### Steps to Reproduce

1. clone https://github.com/petermuessig/ui5.demo.sap_cloud_sdk.http_client
2. change the version of @sap-cloud-sdk/http-client to 4.5.1 on package.json
3. npm install and npm start
4. on chrome console you can see the error for:
Caused by: ModuleError: failed to execute module factory for ''@sap-cloud-sdk/http-client.js'': The "original" argument must be of type Function

and when debugging, we can see it is caused by zlib.brotliCompress being undefined.
const brotliCompress = (0, node_util_1.promisify)(zlib.brotliCompress);

Image

### Expected Behavior

With @sap-cloud-sdk/http-client version 4.4.0 the loading of @sap-cloud-sdk/http-client works ok

### Screenshots

_No response_

### Used Versions

- Node version via `node -v`: ...
- NPM version via `npm -v: ...
- SAP Cloud SDK version: ...
- For CAP users, CAP version: ...

### Code Examples

_No response_

### Log File

_No response_

### Affected Development Phase

Getting Started

### Impact

No Impact

### Timeline

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by davidkna-sap**
Closes #6380

### CODE REVIEW

File: packages/http-client/src/compress-request-middleware.ts [hunk 1]
```diff
@@ -17,25 +17,57 @@ const logger = createLogger({
...
-  deflate: deflateCompress,
-  zstd: zstdCompress
-};
-
-function getSupportedAlgorithms(): string {
-  return Object.entries(compressors)
-    .filter(([, fn]) => fn !== undefined)
-    .map(([name]) => `'${name}'`)
-    .join(', ');
+interface CompressorsMap {
```
Comment (davidkna-sap) [inline packages/http-client/src/compress-request-middleware.ts:20]: Cannot use compressor functions in this type as-is because `zlib` does not have a `promises` variant.
