### PR TITLE
fix: Extend mail client types to accept multiple replyTo recipients.

### LINKED ISSUE #4864: Update replyTo type definition in mail client
**Describe the bug**
Email sending via SAP Cloud SDK is currently being implemented and it has been discovered that the `replyTo` type is not sufficiently defined. It should be updated to `replyTo?: string | Address | (string | Address)[] | undefined;`. This update is necessary to allow the configuration of more than one `replyTo` address. Since the SAP Cloud SDK uses nodemailer, which supports an array for the `replyTo` property, the type definition needs to be adjusted to reflect this capability.

**To Reproduce**
1. Attempt to send an email using the SAP Cloud SDK mail-client with an array of addresses for the `replyTo` property.
2. Observe the TypeScript error due to incorrect type definition.

**Expected behavior**
It should be possible to pass an array of addresses for the `replyTo` property of the `MailConfig` type to the mail-client `sendMail` function, aligned with the capabilities of nodemailer.

**Screenshots**

**Used Versions:**
- node version via `node -v`: v20.11.1
- npm version via `npm -v`: 10.2.4
- SAP Cloud SDK version you used as dependency: @sap-cloud-sdk/mail-client: 3.16.0

**Code Examples**
[Link to code](https://github.com/SAP/cloud-sdk-js/blob/81564c389dd245093c1e4b3c52db69f5aaab8018/packages/mail-client/src/mail-client-types.ts#L122)
If applicable, add code snippets as examples to help explain your problem. Please remove sensitive information.

**Log file**
If applicable, add your log file or related error message. Again, please remove your sensitive information.

**Impact / Priority**
Priority: Low, because we have a workaround
Affected development phase: Development
Impact: Blocked

**Additional context**

### PR DESCRIPTION
**Pull request by mgnther**
This adapts the MailConfig type in the mail-client package to accept multiple replyTo addresses to send mails with multiple replyTo recipients. This change is compatible to the types of nodemailer package (see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/178c0cdae8e88a48e01be8437175cc014b0be473/types/nodemailer/lib/mailer/index.d.ts#L110).

Closes #4864.

### CODE REVIEW

**Comment by deekshas8** [comment]
Hi @hagendaehne ,

Thank you for catching this and raising a PR. I'll add a changeset and then we're good to go.

File: packages/mail-client/src/mail-client-types.ts [hunk 1]
```diff
@@ -119,7 +119,7 @@ export interface MailConfig {
   /**
    * E-mail address that will appear in the "Reply-To:" field.
```
Comment (deekshas8) [inline packages/mail-client/src/mail-client-types.ts:120]:
```suggestion
   * Comma separated list or array of e-mail addresses that will appear in the "Reply-To:" field.
```

**Review by deekshas8 — APPROVED** [review]
